import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import InteractiveStrings from "@/components/InteractiveStrings";
import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="flex flex-col p-2 min-h-screen bg-gray-700">
			<noscript>
				<style>{`
					.typewriter-fallback { opacity: 1 !important; }
				`}</style>
			</noscript>
				<InteractiveStrings />
				<NavigationBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
